---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediapp-deployment
spec:
  replicas: 2   
  selector:
    matchLabels:
      type: front-end
      app: mediapp
  template:
    metadata:
      labels:
        type: front-end
        app: mediapp
    spec:
      containers:
        - name: mediapp
          image: zenitugo/medicalsite
          ports:
            - containerPort: 80
      

