---
apiVersion: v1
kind: Service
metadata:
  name: mediapp-external-service
spec:
  selector:
    app: mediapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodeport: 31515
  